#!/usr/bin/env node
// Reads DESIGN.md frontmatter and emits a Tailwind v4 `@theme` block to
// src/styles/theme.css. The upstream `@google/design.md` CLI only exports
// Tailwind v3-style JSON, so we maintain this v4-compatible exporter locally.
// See DECISIONS.md (ADR-015) for the rationale.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import yaml from 'js-yaml';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const designPath = path.join(root, 'DESIGN.md');
const outPath = path.join(root, 'src/styles/theme.css');

const raw = readFileSync(designPath, 'utf8');
const match = raw.match(/^---\n([\s\S]*?)\n---/);
if (!match) {
  console.error('Could not find YAML frontmatter in DESIGN.md');
  process.exit(1);
}

const fm = yaml.load(match[1]);

const lines = [];
lines.push('/* Generated by scripts/design-export.mjs from DESIGN.md — do not edit by hand. */');
lines.push('/* Run `npm run design:export` to regenerate. */');
lines.push('@import "tailwindcss";');
lines.push('');
lines.push('@theme {');

const colors = fm.colors ?? {};
for (const [name, value] of Object.entries(colors)) {
  lines.push(`  --color-${name}: ${value};`);
}
lines.push('');

const spacing = fm.spacing ?? {};
for (const [name, value] of Object.entries(spacing)) {
  lines.push(`  --spacing-${name}: ${value};`);
}
lines.push('');

const rounded = fm.rounded ?? {};
for (const [name, value] of Object.entries(rounded)) {
  lines.push(`  --radius-${name}: ${value};`);
}
lines.push('');

const typography = fm.typography ?? {};
const familySet = new Map();
for (const [, scale] of Object.entries(typography)) {
  if (scale?.fontFamily) {
    const family = scale.fontFamily.split(',')[0].trim();
    familySet.set(family.toLowerCase(), scale.fontFamily);
  }
}
for (const [, family] of familySet) {
  const first = family.split(',')[0].trim().toLowerCase();
  lines.push(`  --font-${first}: ${family};`);
}
lines.push('');

for (const [name, scale] of Object.entries(typography)) {
  if (scale?.fontSize) {
    lines.push(`  --text-${name}: ${scale.fontSize};`);
  }
  if (scale?.lineHeight !== undefined) {
    lines.push(`  --leading-${name}: ${scale.lineHeight};`);
  }
  if (scale?.letterSpacing !== undefined) {
    lines.push(`  --tracking-${name}: ${scale.letterSpacing};`);
  }
  if (scale?.fontWeight !== undefined) {
    lines.push(`  --font-weight-${name}: ${scale.fontWeight};`);
  }
}

lines.push('}');
lines.push('');

writeFileSync(outPath, lines.join('\n'));
console.log(`Wrote ${outPath} (${lines.length} lines, ${Object.keys(colors).length} colors, ${Object.keys(typography).length} type scales).`);
