#!/usr/bin/env node
// Reads DESIGN.md frontmatter and emits a Tailwind v4 `@theme` block to
// src/styles/theme.css. The upstream `@google/design.md` CLI only exports
// Tailwind v3-style JSON, so we maintain this v4-compatible exporter locally.
// See DECISIONS.md (ADR-015) for the rationale.
//
// Hardening (per Codex round 1, findings #1 and #4):
//   - Validates that the parsed frontmatter has the required top-level shape
//     before emitting anything. Better to fail loudly than to write half a
//     theme.css and silently break the next build.
//   - Writes to a sibling .tmp file and renames atomically so a crash mid-
//     write can never corrupt theme.css for the dev server / build.
//   - Emits a `--font-{role}` alias for every typography role in DESIGN.md
//     (display, h1, body-md, label-caps, …) so role-name Tailwind utilities
//     like `font-display` / `font-label-caps` work natively, not just the
//     two literal family names.

import { readFileSync, writeFileSync, renameSync, unlinkSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import yaml from 'js-yaml';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const designPath = path.join(root, 'DESIGN.md');
const outPath = path.join(root, 'src/styles/theme.css');
const tmpPath = `${outPath}.tmp`;

function fail(message) {
  console.error(`design-export: ${message}`);
  process.exit(1);
}

function assertObject(value, label) {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) {
    fail(`expected '${label}' to be a mapping in DESIGN.md frontmatter`);
  }
}

const raw = readFileSync(designPath, 'utf8');
const match = raw.match(/^---\n([\s\S]*?)\n---/);
if (!match) {
  fail('could not find YAML frontmatter in DESIGN.md (expected --- delimited block at the top of the file)');
}

let fm;
try {
  fm = yaml.load(match[1]);
} catch (err) {
  fail(`YAML parse failed: ${err.message}`);
}

assertObject(fm, 'frontmatter');
assertObject(fm.colors, 'colors');
assertObject(fm.spacing, 'spacing');
assertObject(fm.rounded, 'rounded');
assertObject(fm.typography, 'typography');

const lines = [];
lines.push('/* Generated by scripts/design-export.mjs from DESIGN.md — do not edit by hand. */');
lines.push('/* Run `npm run design:export` to regenerate. */');
lines.push('@import "tailwindcss";');
lines.push('');
lines.push('@theme {');

for (const [name, value] of Object.entries(fm.colors)) {
  lines.push(`  --color-${name}: ${value};`);
}
lines.push('');

for (const [name, value] of Object.entries(fm.spacing)) {
  lines.push(`  --spacing-${name}: ${value};`);
}
lines.push('');

// CRITICAL: emit Tailwind v4's --container-* scale explicitly. Otherwise
// max-w-{xs|sm|md|lg|xl|2xl|3xl} utilities fall back to var(--spacing-{key})
// — and since DESIGN.md defines a spacing scale with the SAME keys
// (xs/sm/md/lg/xl/2xl/3xl), max-w-xl resolves to 64px instead of 576px,
// max-w-md to 16px instead of 448px, etc. This caused every body
// paragraph using max-w-{md,xl,2xl,3xl} to collapse to a 4-144px column
// and wrap one word per line across 23 components site-wide. (See
// /tmp/gw-audit/AUDIT.md root-cause section.)
const containers = [
  ['3xs', '16rem'],   // 256px
  ['2xs', '18rem'],   // 288px
  ['xs',  '20rem'],   // 320px
  ['sm',  '24rem'],   // 384px
  ['md',  '28rem'],   // 448px
  ['lg',  '32rem'],   // 512px
  ['xl',  '36rem'],   // 576px
  ['2xl', '42rem'],   // 672px
  ['3xl', '48rem'],   // 768px
  ['4xl', '56rem'],   // 896px
  ['5xl', '64rem'],   // 1024px
  ['6xl', '72rem'],   // 1152px
  ['7xl', '80rem'],   // 1280px
];
for (const [name, value] of containers) {
  lines.push(`  --container-${name}: ${value};`);
}
lines.push('');

for (const [name, value] of Object.entries(fm.rounded)) {
  lines.push(`  --radius-${name}: ${value};`);
}
lines.push('');

// Emit `--font-{slug}` for every unique font-family stack in DESIGN.md
// (typically two: Fraunces, Inter). Slugify the var-name token: strip
// quotes, lowercase, replace whitespace with hyphens, and drop the
// "-variable" suffix that fontsource adds — so `"Fraunces Variable"`
// becomes `--font-fraunces`, not the invalid `--font-fraunces variable`.
function slugifyFamily(name) {
  return name
    .replace(/['"]/g, '')
    .trim()
    .toLowerCase()
    .replace(/\s+variable$/, '')
    .replace(/\s+/g, '-');
}
const familySet = new Map();
for (const scale of Object.values(fm.typography)) {
  if (scale?.fontFamily) {
    const first = scale.fontFamily.split(',')[0];
    const slug = slugifyFamily(first);
    familySet.set(slug, scale.fontFamily);
  }
}
for (const [slug, family] of familySet) {
  lines.push(`  --font-${slug}: ${family};`);
}

// Also emit `--font-{role}` aliases (display, h1, h2, h3, body-lg, body-md,
// body-sm, label-caps, serif-quote, …) so role-name utilities work. This is
// what Codex round 1 finding #4 caught — without it, `font-display` in a
// component doesn't resolve and only renders correctly when global.css sets
// the family explicitly on the element.
for (const [role, scale] of Object.entries(fm.typography)) {
  if (scale?.fontFamily) {
    lines.push(`  --font-${role}: ${scale.fontFamily};`);
  }
}
lines.push('');

for (const [name, scale] of Object.entries(fm.typography)) {
  if (scale?.fontSize !== undefined) {
    lines.push(`  --text-${name}: ${scale.fontSize};`);
  }
  if (scale?.lineHeight !== undefined) {
    lines.push(`  --leading-${name}: ${scale.lineHeight};`);
  }
  if (scale?.letterSpacing !== undefined) {
    lines.push(`  --tracking-${name}: ${scale.letterSpacing};`);
  }
  if (scale?.fontWeight !== undefined) {
    lines.push(`  --font-weight-${name}: ${scale.fontWeight};`);
  }
}

lines.push('}');
lines.push('');

try {
  writeFileSync(tmpPath, lines.join('\n'));
  renameSync(tmpPath, outPath);
} catch (err) {
  try { unlinkSync(tmpPath); } catch { /* tmp may not exist; ignore */ }
  fail(`failed to write ${outPath}: ${err.message}`);
}

const fontCount = familySet.size + Object.keys(fm.typography).filter((r) => fm.typography[r]?.fontFamily).length;
console.log(
  `Wrote ${outPath} — ${Object.keys(fm.colors).length} colors, ${Object.keys(fm.typography).length} type scales, ${fontCount} font tokens.`,
);
